### ISSUE TITLE
Using threads

### ISSUE THREAD

**Issue by suvenduat** [JohannesBuchner/jbopt#1]
Hi Johannes, 
I am trying jbopt. Could not find which keyword can be given in the dictionary "problem"?Is it possible to use multiple thread in jbopt.mcmc?  Is it accept all the options that emcee accept?
Thanks.

Regards,
Suvendu

**Comment by JohannesBuchner** [comment]
Sorry, I do not provide support for jbopt, except for pull requests on adding or improving interfaces. 
Please refer to 
http://johannesbuchner.github.io/jbopt/doc.html
http://johannesbuchner.github.io/jbopt/example.html
and the source code. 

Multithreading is currently not supported for the mcmc module.
